# Generated by Django 3.1.7 on 2021-03-07 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='[01]')], verbose_name='システム利用可否')),
                ('debug', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='[01]')], verbose_name='デバッグモード')),
                ('last_update', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='\\d{4}/\\d{2}/\\d{2}_\\d{2}:\\d{2}:\\d{2}')], verbose_name='最終更新')),
            ],
        ),
    ]
