# Generated by Django 3.1.7 on 2021-03-07 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0002_systemcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcondition',
            name='available',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='[0-1]')], verbose_name='システム利用可否'),
        ),
        migrations.AlterField(
            model_name='systemcondition',
            name='debug',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='[0-1]')], verbose_name='デバッグモード'),
        ),
    ]
