# Generated by Django 3.1.7 on 2021-03-08 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0004_reservationplan_reservationtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtarget',
            name='gno',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='号面'),
        ),
        migrations.AddField(
            model_name='reservationtarget',
            name='gno_csv',
            field=models.CharField(default='', max_length=15, verbose_name='号面CSV'),
        ),
    ]
