# Generated by Django 3.1.7 on 2021-03-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0005_auto_20210308_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationplan',
            name='area_csv',
            field=models.CharField(default='', max_length=80, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='reservationplan',
            name='ymd_range',
            field=models.CharField(default='', max_length=17, verbose_name='年月日範囲'),
        ),
    ]
