# Generated by Django 3.1.7 on 2021-03-11 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0006_auto_20210308_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationplan',
            name='reserved_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(3)], verbose_name='予約済み数'),
        ),
        migrations.AddField(
            model_name='reservationplan',
            name='target_cnt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(3)], verbose_name='ターゲット数'),
        ),
    ]
