# Generated by Django 3.1.7 on 2021-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0009_auto_20210316_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationtarget',
            name='gno',
        ),
        migrations.AddField(
            model_name='reservationtarget',
            name='reserve_gno_csv',
            field=models.CharField(default='', max_length=40, verbose_name='予約済み号面CSV'),
        ),
    ]
