# Generated by Django 3.1.7 on 2021-03-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0010_auto_20210316_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationplan',
            name='author',
            field=models.CharField(default='', max_length=5, verbose_name='作成者'),
        ),
    ]
