# Generated by Django 3.1.7 on 2021-03-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0011_reservationplan_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationWeeklyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=1, verbose_name='曜日')),
                ('target_json', models.CharField(max_length=3000, verbose_name='ターゲット設定JSON')),
            ],
        ),
    ]
