# Generated by Django 3.1.7 on 2021-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0012_reservationweeklytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcondition',
            name='week_targets',
            field=models.CharField(default='', max_length=20, verbose_name='曜日ターゲット'),
        ),
    ]
