# Generated by Django 3.1.7 on 2021-03-24 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0013_systemcondition_week_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcondition',
            name='account',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(regex='\\d+')], verbose_name='アカウント'),
        ),
        migrations.AddField(
            model_name='systemcondition',
            name='pswd',
            field=models.CharField(default='', max_length=50, verbose_name='パスワード'),
        ),
    ]
