# Generated by Django 3.1.7 on 2021-03-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0015_reservationweeklytarget_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationweeklytarget',
            old_name='available',
            new_name='enable',
        ),
    ]
