# Generated by Django 3.1.7 on 2021-03-28 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0016_auto_20210327_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_no', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(8)], verbose_name='予約番号')),
                ('g_no', models.CharField(max_length=1, verbose_name='号面')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ground_view.reservationtarget')),
            ],
        ),
    ]
