# Generated by Django 3.1.7 on 2021-03-29 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0017_reservationresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationresult',
            name='g_no',
        ),
        migrations.AddField(
            model_name='reservationresult',
            name='timebox',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='時間帯'),
        ),
    ]
