# Generated by Django 3.1.7 on 2021-03-29 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0018_auto_20210329_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationresult',
            name='g_no',
            field=models.CharField(default=None, max_length=1, verbose_name='号面'),
        ),
        migrations.AlterField(
            model_name='reservationresult',
            name='timebox',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='時間帯'),
        ),
    ]
