# Generated by Django 3.1.7 on 2021-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0019_auto_20210329_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=25, verbose_name='ユーザー名')),
                ('password', models.CharField(default='', max_length=25, verbose_name='パスワード')),
            ],
        ),
    ]
