# Generated by Django 3.1.7 on 2021-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0020_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationplan',
            name='user_id',
            field=models.CharField(default='', max_length=2, verbose_name='ユーザーID'),
        ),
    ]
