# Generated by Django 3.1.7 on 2021-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_view', '0024_reservationweeklytarget_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationresult',
            name='g_no',
            field=models.CharField(default=None, max_length=2, verbose_name='号面'),
        ),
    ]
